### ISSUE TITLE
Don't link empty Categories

### ISSUE THREAD

**Issue by xstable** [osclass/theme-bender#45]
Please change Template, so that empty categories (on Startpage) are not linked to #.

To got it go to functions.php Line 245 (inside the else-block) and change it to the following: 

With this: 
```php
<?php } else { ?>
    <span><?php echo osc_category_name() ; ?> (<?php echo osc_category_total_items() ; ?>)/span>
<?php } ?>
```

If you like to have some eyecandy (Categories with content blue, empty-categories gray) to got a better overwiew (example see this image: http://pix.toile-libre.org/upload/original/1424453874.jpg ) change styles in main.css: 
```css
body #main{font-family:arial}
.r-list li {color: rgb(177, 177, 177);}
select#sCategory {height: 43px;}
```
